import type { AchievementBadgeDefinition, AchievementId } from './types';

export const ACHIEVEMENT_BADGES = [
  {
    id: 'first-session',
    title: 'First Contact',
    description: 'Completed your first group training session.',
    criteria: 'Finish one Group training session.',
    tier: 'bronze',
    rarity: 'common',
    category: 'consistency',
  },
  {
    id: 'first-letter',
    title: 'First Letter',
    description: 'Mastered your first Morse letter.',
    criteria: 'Reach 90% accuracy over at least 5 attempts on any letter.',
    tier: 'bronze',
    rarity: 'common',
    category: 'mastery',
  },
  {
    id: 'first-digit',
    title: 'First Digit',
    description: 'Mastered your first Morse digit.',
    criteria: 'Reach 90% accuracy over at least 5 attempts on any digit.',
    tier: 'bronze',
    rarity: 'uncommon',
    category: 'mastery',
  },
  {
    id: 'quarter-alphabet',
    title: 'Quarter Alphabet',
    description: 'Built a foundation across the alphabet.',
    criteria: 'Master at least 25% of A-Z.',
    tier: 'silver',
    rarity: 'uncommon',
    category: 'mastery',
  },
  {
    id: 'half-alphabet',
    title: 'Half Alphabet',
    description: 'Mastered half of the Morse alphabet.',
    criteria: 'Master at least 50% of A-Z.',
    tier: 'silver',
    rarity: 'rare',
    category: 'mastery',
  },
  {
    id: 'three-quarter-alphabet',
    title: 'Three Quarter Alphabet',
    description: 'Can copy most letters with confidence.',
    criteria: 'Master at least 75% of A-Z.',
    tier: 'gold',
    rarity: 'rare',
    category: 'mastery',
  },
  {
    id: 'full-alphabet',
    title: 'Full Alphabet',
    description: 'Mastered every letter from A to Z.',
    criteria: 'Master all 26 letters.',
    tier: 'platinum',
    rarity: 'epic',
    category: 'mastery',
  },
  {
    id: 'clean-copy',
    title: 'Clean Copy',
    description: 'Copied a whole session without a miss.',
    criteria: 'Finish a Group session with 100% accuracy and at least 25 characters.',
    tier: 'silver',
    rarity: 'uncommon',
    category: 'performance',
  },
  {
    id: 'ninety-club',
    title: 'Ninety Club',
    description: 'Kept accuracy high on a meaningful character set.',
    criteria: 'Score 90%+ with at least 10 effective characters.',
    tier: 'silver',
    rarity: 'rare',
    category: 'performance',
  },
  {
    id: 'pressure-copy',
    title: 'Pressure Copy',
    description: 'Copied quickly while staying accurate.',
    criteria: 'Score 90%+ with average response under 1500 ms.',
    tier: 'gold',
    rarity: 'rare',
    category: 'performance',
  },
  {
    id: 'long-haul',
    title: 'Long Haul',
    description: 'Stayed sharp through a longer run.',
    criteria: 'Score 90%+ across at least 100 characters.',
    tier: 'gold',
    rarity: 'rare',
    category: 'performance',
  },
  {
    id: 'three-day-streak',
    title: 'Three Day Streak',
    description: 'Practiced Group training three days in a row.',
    criteria: 'Complete Group sessions on 3 consecutive days.',
    tier: 'bronze',
    rarity: 'uncommon',
    category: 'consistency',
  },
  {
    id: 'seven-day-streak',
    title: 'Seven Day Streak',
    description: 'Made Morse practice a habit.',
    criteria: 'Complete Group sessions on 7 consecutive days.',
    tier: 'gold',
    rarity: 'epic',
    category: 'consistency',
  },
  {
    id: 'comeback',
    title: 'Comeback',
    description: 'Returned after a break and copied well.',
    criteria: 'After 7+ days away, complete a session at 80%+ accuracy.',
    tier: 'silver',
    rarity: 'rare',
    category: 'consistency',
  },
  {
    id: 'score-1000',
    title: 'Kilopoint',
    description: 'Broke 1,000 points in a session.',
    criteria: 'Earn a session score of at least 1,000.',
    tier: 'bronze',
    rarity: 'common',
    category: 'score',
  },
  {
    id: 'score-2500',
    title: 'High Voltage',
    description: 'Broke 2,500 points in a session.',
    criteria: 'Earn a session score of at least 2,500.',
    tier: 'silver',
    rarity: 'rare',
    category: 'score',
  },
  {
    id: 'score-5000',
    title: 'Signal Legend',
    description: 'Broke 5,000 points in a session.',
    criteria: 'Earn a session score of at least 5,000.',
    tier: 'platinum',
    rarity: 'epic',
    category: 'score',
  },
] as const satisfies readonly AchievementBadgeDefinition[];

export const ACHIEVEMENT_BADGE_BY_ID: Readonly<Record<AchievementId, AchievementBadgeDefinition>> =
  ACHIEVEMENT_BADGES.reduce(
    (acc, badge) => ({
      ...acc,
      [badge.id]: badge,
    }),
    {} as Record<AchievementId, AchievementBadgeDefinition>,
  );
