import type { AchievementBadgeDefinition, AchievementId } from './types';

export const ACHIEVEMENT_BADGES = [
  {
    id: 'first-session',
    title: 'First Contact',
    description: 'Completed your first group training session.',
    criteria: 'Finish one Group training session.',
    tier: 'bronze',
    rarity: 'common',
    category: 'consistency',
  },
  {
    id: 'getting-warm',
    title: 'Getting Warm',
    description: 'Built a regular practice rhythm.',
    criteria: 'Complete 10 Group training sessions.',
    tier: 'bronze',
    rarity: 'common',
    category: 'consistency',
  },
  {
    id: 'first-letter',
    title: 'First Letter',
    description: 'Mastered your first Morse letter.',
    criteria: 'Reach 90% accuracy over at least 5 attempts on any letter.',
    tier: 'bronze',
    rarity: 'common',
    category: 'mastery',
  },
  {
    id: 'first-digit',
    title: 'First Digit',
    description: 'Mastered your first Morse digit.',
    criteria: 'Reach 90% accuracy over at least 5 attempts on any digit.',
    tier: 'bronze',
    rarity: 'uncommon',
    category: 'mastery',
  },
  {
    id: 'number-pad',
    title: 'Number Pad',
    description: 'Mastered half the Morse digits.',
    criteria: 'Master at least 5 digits (0-9).',
    tier: 'silver',
    rarity: 'uncommon',
    category: 'mastery',
  },
  {
    id: 'full-keypad',
    title: 'Full Keypad',
    description: 'Mastered every Morse digit.',
    criteria: 'Master all 10 digits.',
    tier: 'gold',
    rarity: 'rare',
    category: 'mastery',
  },
  {
    id: 'quarter-alphabet',
    title: 'Quarter Alphabet',
    description: 'Built a foundation across the alphabet.',
    criteria: 'Master at least 25% of A-Z.',
    tier: 'silver',
    rarity: 'uncommon',
    category: 'mastery',
  },
  {
    id: 'half-alphabet',
    title: 'Half Alphabet',
    description: 'Mastered half of the Morse alphabet.',
    criteria: 'Master at least 50% of A-Z.',
    tier: 'silver',
    rarity: 'rare',
    category: 'mastery',
  },
  {
    id: 'three-quarter-alphabet',
    title: 'Three Quarter Alphabet',
    description: 'Can copy most letters with confidence.',
    criteria: 'Master at least 75% of A-Z.',
    tier: 'gold',
    rarity: 'rare',
    category: 'mastery',
  },
  {
    id: 'full-alphabet',
    title: 'Full Alphabet',
    description: 'Mastered every letter from A to Z.',
    criteria: 'Master all 26 letters.',
    tier: 'platinum',
    rarity: 'epic',
    category: 'mastery',
  },
  {
    id: 'clean-copy',
    title: 'Clean Copy',
    description: 'Copied a whole session without a miss.',
    criteria: 'Finish a Group session with 100% accuracy and at least 25 characters.',
    tier: 'silver',
    rarity: 'uncommon',
    category: 'performance',
  },
  {
    id: 'flawless-run',
    title: 'Flawless Run',
    description: 'Copied a long session without a single error.',
    criteria: 'Finish a Group session with 100% accuracy and at least 50 characters.',
    tier: 'gold',
    rarity: 'rare',
    category: 'performance',
  },
  {
    id: 'ninety-club',
    title: 'Ninety Club',
    description: 'Kept accuracy high on a meaningful character set.',
    criteria: 'Score 90%+ with at least 10 effective characters.',
    tier: 'silver',
    rarity: 'rare',
    category: 'performance',
  },
  {
    id: 'pressure-copy',
    title: 'Pressure Copy',
    description: 'Copied quickly while staying accurate.',
    criteria: 'Score 90%+ with average response under 1500 ms.',
    tier: 'gold',
    rarity: 'rare',
    category: 'performance',
  },
  {
    id: 'lightning-copy',
    title: 'Lightning Copy',
    description: 'Copied at high speed with precision.',
    criteria: 'Score 90%+ with average response under 1000 ms.',
    tier: 'platinum',
    rarity: 'epic',
    category: 'performance',
  },
  {
    id: 'long-haul',
    title: 'Long Haul',
    description: 'Stayed sharp through a longer run.',
    criteria: 'Score 90%+ across at least 100 characters.',
    tier: 'gold',
    rarity: 'rare',
    category: 'performance',
  },
  {
    id: 'three-day-streak',
    title: 'Three Day Streak',
    description: 'Practiced Group training three days in a row.',
    criteria: 'Complete Group sessions on 3 consecutive days.',
    tier: 'bronze',
    rarity: 'uncommon',
    category: 'consistency',
  },
  {
    id: 'seven-day-streak',
    title: 'Seven Day Streak',
    description: 'Made Morse practice a habit.',
    criteria: 'Complete Group sessions on 7 consecutive days.',
    tier: 'silver',
    rarity: 'uncommon',
    category: 'consistency',
  },
  {
    id: 'regular',
    title: 'Regular',
    description: 'Kept the key warm for two full weeks.',
    criteria: 'Complete Group sessions on 14 consecutive days.',
    tier: 'silver',
    rarity: 'rare',
    category: 'consistency',
  },
  {
    id: 'three-week-streak',
    title: 'Three Week Streak',
    description: 'Practiced every day for three full weeks.',
    criteria: 'Complete Group sessions on 21 consecutive days.',
    tier: 'silver',
    rarity: 'rare',
    category: 'consistency',
  },
  {
    id: 'monthly-operator',
    title: 'Monthly Operator',
    description: 'Copied Morse every day for a full month.',
    criteria: 'Complete Group sessions on 30 consecutive days.',
    tier: 'gold',
    rarity: 'rare',
    category: 'consistency',
  },
  {
    id: 'steadfast',
    title: 'Steadfast',
    description: 'Never missed a day for six weeks straight.',
    criteria: 'Complete Group sessions on 45 consecutive days.',
    tier: 'gold',
    rarity: 'epic',
    category: 'consistency',
  },
  {
    id: 'iron-routine',
    title: 'Iron Routine',
    description: 'Two months of daily practice without a gap.',
    criteria: 'Complete Group sessions on 60 consecutive days.',
    tier: 'gold',
    rarity: 'epic',
    category: 'consistency',
  },
  {
    id: 'quarter-year',
    title: 'Quarter Year',
    description: 'Kept the streak alive for three months.',
    criteria: 'Complete Group sessions on 90 consecutive days.',
    tier: 'platinum',
    rarity: 'epic',
    category: 'consistency',
  },
  {
    id: 'half-year',
    title: 'Half Year',
    description: 'Six months of unbroken daily practice.',
    criteria: 'Complete Group sessions on 180 consecutive days.',
    tier: 'platinum',
    rarity: 'epic',
    category: 'consistency',
  },
  {
    id: 'full-year',
    title: 'Full Year',
    description: 'A full calendar year without missing a single day.',
    criteria: 'Complete Group sessions on 365 consecutive days.',
    tier: 'diamond',
    rarity: 'epic',
    category: 'consistency',
  },
  {
    id: 'daily-operator',
    title: 'Daily Operator',
    description: 'Practiced on many different days.',
    criteria: 'Complete Group sessions on 10 distinct days.',
    tier: 'bronze',
    rarity: 'uncommon',
    category: 'consistency',
  },
  {
    id: 'comeback',
    title: 'Comeback',
    description: 'Returned after a break and copied well.',
    criteria: 'After 7+ days away, complete a session at 80%+ accuracy.',
    tier: 'silver',
    rarity: 'rare',
    category: 'consistency',
  },
  {
    id: 'score-1000',
    title: 'Kilopoint',
    description: 'Broke 1,000 points in a session.',
    criteria: 'Earn a session score of at least 1,000.',
    tier: 'bronze',
    rarity: 'common',
    category: 'score',
  },
  {
    id: 'score-2500',
    title: 'High Voltage',
    description: 'Broke 2,500 points in a session.',
    criteria: 'Earn a session score of at least 2,500.',
    tier: 'silver',
    rarity: 'rare',
    category: 'score',
  },
  {
    id: 'score-5000',
    title: 'Signal Legend',
    description: 'Broke 5,000 points in a session.',
    criteria: 'Earn a session score of at least 5,000.',
    tier: 'platinum',
    rarity: 'epic',
    category: 'score',
  },
  {
    id: 'megawatt',
    title: 'Megawatt',
    description: 'Pushed session scoring into overdrive.',
    criteria: 'Earn a session score of at least 7,500.',
    tier: 'gold',
    rarity: 'epic',
    category: 'score',
  },
  {
    id: 'koch-graduate',
    title: 'Koch Graduate',
    description: 'Copied confidently at the full Koch curriculum.',
    criteria: 'Finish a Group session at Koch level 40 with 80%+ accuracy.',
    tier: 'platinum',
    rarity: 'epic',
    category: 'mastery',
  },
  {
    id: 'solid-copy-5wpm',
    title: 'Novice Copy (5 WPM)',
    description: 'Solid copy over the full alphabet at 5 WPM — the historic Novice test.',
    criteria: 'In one full-alphabet session, copy 100+ characters correctly at ≥5 WPM with ≥90% accuracy.',
    tier: 'silver',
    rarity: 'uncommon',
    category: 'performance',
  },
  {
    id: 'solid-copy-13wpm',
    title: 'General Copy (13 WPM)',
    description: 'Solid copy over the full alphabet at 13 WPM — the historic General test.',
    criteria: 'In one full-alphabet session, copy 100+ characters correctly at ≥13 WPM with ≥90% accuracy.',
    tier: 'gold',
    rarity: 'rare',
    category: 'performance',
  },
  {
    id: 'solid-copy-20wpm',
    title: 'Extra Copy (20 WPM)',
    description: 'Solid copy over the full alphabet at 20 WPM — the historic Amateur Extra test.',
    criteria: 'In one full-alphabet session, copy 100+ characters correctly at ≥20 WPM with ≥90% accuracy.',
    tier: 'diamond',
    rarity: 'epic',
    category: 'performance',
  },
] as const satisfies readonly AchievementBadgeDefinition[];

export const ACHIEVEMENT_BADGE_BY_ID: Readonly<Record<AchievementId, AchievementBadgeDefinition>> =
  ACHIEVEMENT_BADGES.reduce(
    (acc, badge) => ({
      ...acc,
      [badge.id]: badge,
    }),
    {} as Record<AchievementId, AchievementBadgeDefinition>,
  );
