import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';

/**
 * Version information generated at build time from git tags and commit hash.
 * This file is generated by scripts/generate-version.js during the build process.
 */

export interface VersionInfo {
  version: string;
  versionType: 'release' | 'dev' | 'unknown';
  tag: string | null;
  hash: string;
  isDirty: boolean;
  isTagged: boolean;
  buildTime: string;
}

let versionInfo: VersionInfo | null = null;

/**
 * Gets the version information.
 * In development, this will attempt to read from the generated file.
 * In production, the version info is embedded at build time.
 */
export function getVersionInfo(): VersionInfo {
  if (versionInfo) {
    return versionInfo;
  }

  try {
    // Read generated version.json when available (local build/dev).
    const versionPath = path.join(process.cwd(), 'lib', 'version.json');
    if (!existsSync(versionPath)) {
      throw new Error('version.json not found');
    }
    const versionData = JSON.parse(readFileSync(versionPath, 'utf-8')) as VersionInfo;
    versionInfo = versionData;
    return versionInfo;
  } catch {
    // Fallback if version.json doesn't exist (e.g., first build, not built yet)
    versionInfo = {
      version: 'dev',
      versionType: 'unknown',
      tag: null,
      hash: 'unknown',
      isDirty: false,
      isTagged: false,
      buildTime: new Date().toISOString(),
    };
    return versionInfo;
  }
}

/**
 * Gets a formatted version string for display.
 */
export function getVersionString(): string {
  const info = getVersionInfo();
  return info.version;
}

/**
 * Gets a human-readable version description.
 */
export function getVersionDescription(): string {
  const info = getVersionInfo();
  if (info.versionType === 'release') {
    return `Version ${info.version}`;
  } else if (info.versionType === 'dev') {
    return `Development build (${info.version})`;
  }
  return 'Version unknown';
}
