import type { IcrSettings, TrainingSettings } from '@/types';

export const DEFAULT_TRAINING_SETTINGS: TrainingSettings = {
  kochLevel: 1, // Level 1 = 2 characters, Level 2 = 3 characters, etc.
  charSetMode: 'koch',
  digitsLevel: 10,
  mixedLettersPercent: 70,
  customSet: [],
  slidingWindowStart: 1,
  slidingWindowEnd: 40,
  sideToneMin: 600,
  sideToneMax: 600,
  volumeMin: 1,
  volumeMax: 1,
  linkVolume: true,
  steepness: 5,
  sessionDuration: 5,
  charsPerGroup: 5,
  numGroups: 5,
  charWpmMin: 23,
  charWpmMax: 23,
  linkCharWpm: true,
  effectiveWpmMin: 23,
  effectiveWpmMax: 23,
  linkEffectiveWpm: true,
  linkCharToEffective: true,
  echoKeyerMode: 'manual',
  extraWordSpaceMultiplier: 1,
  groupTimeout: 10,
  minGroupSize: 2,
  maxGroupSize: 3,
  linkGroupSize: false,
  envelopeSmoothing: 0,
  autoAdjustKoch: false,
  autoAdjustThreshold: 90,
  autoAdjustBelowThresholdCount: 0,
  autoAdjustAboveThresholdCount: 0,
  echoAutoAdjustKoch: false,
  echoAutoAdjustThreshold: 90,
  echoAutoAdjustBelowThresholdCount: 0,
  echoAutoAdjustAboveThresholdCount: 0,
  errorWeightStrength: 0,
};

export const DEFAULT_ICR_SETTINGS: IcrSettings = {
  trialsPerSession: 30,
  trialDelayMs: 700,
  vadEnabled: true,
  vadThreshold: 0.08,
  vadHoldMs: 60,
  bucketGreenMaxMs: 400,
  bucketYellowMaxMs: 600,
  bucketOrangeMaxMs: 800,
};
