import type { IcrSettings, TrainingSettings } from '@/types';

export const DEFAULT_TRAINING_SETTINGS: TrainingSettings = {
  kochLevel: 1, // Level 1 = 2 characters, Level 2 = 3 characters, etc.
  charSetMode: 'koch',
  digitsLevel: 10,
  mixedLettersPercent: 70,
  customSet: [],
  slidingWindowStart: 1,
  slidingWindowEnd: 40,
  sideToneMin: 600,
  sideToneMax: 600,
  volumeMin: 1,
  volumeMax: 1,
  linkVolume: true,
  steepness: 5,
  sessionDuration: 5,
  charsPerGroup: 5,
  numGroups: 5,
  charWpmMin: 23,
  charWpmMax: 23,
  linkCharWpm: true,
  effectiveWpmMin: 23,
  effectiveWpmMax: 23,
  linkEffectiveWpm: true,
  linkCharToEffective: true,
  echoKeyerMode: 'manual',
  extraWordSpaceMultiplier: 1,
  groupTimeout: 10,
  lockInputDuringGroupPlayback: true,
  minGroupSize: 2,
  maxGroupSize: 3,
  linkGroupSize: false,
  envelopeSmoothing: 0,
  qsbEnabled: false,
  qsbDepth: 0.35,
  qsbRateHz: 0.12,
  qrnEnabled: false,
  qrnLevel: 0.25,
  qrmEnabled: false,
  qrmLevel: 0.2,
  qrmProfile: 'mixed',
  receiverBackgroundGain: 20,
  receiverBackgroundExcitationRate: 62,
  receiverBackgroundResonance: 66,
  receiverBackgroundDecay: 0.984,
  receiverBackgroundOffsetHz: 140,
  receiverBackgroundOffsetModDepthHz: 45,
  receiverBackgroundOffsetModRateHz: 0.32,
  autoAdjustKoch: false,
  autoAdjustThreshold: 90,
  autoAdjustBelowThresholdCount: 0,
  autoAdjustAboveThresholdCount: 0,
  echoAutoAdjustKoch: false,
  echoAutoAdjustThreshold: 90,
  echoAutoAdjustBelowThresholdCount: 0,
  echoAutoAdjustAboveThresholdCount: 0,
  chaseLives: 3,
  chaseAutoLevelEnabled: true,
  chaseGroupsPerLevel: 5,
  chaseStartFallMs: 7200,
  chaseMinFallMs: 1800,
  chaseLevelSpeedupMs: 430,
  chaseGroupSpeedupMs: 28,
  errorWeightStrength: 0,
  playerAnnounceLetters: false,
  playerLetterRepeatCount: 1,
  playerRandomizeLetters: false,
  playerDelaySeconds: 2,
  playerSpeechVoiceURI: '',
};

export const DEFAULT_ICR_SETTINGS: IcrSettings = {
  trialsPerSession: 30,
  trialDelayMs: 700,
  vadEnabled: true,
  vadThreshold: 0.08,
  vadHoldMs: 60,
  bucketGreenMaxMs: 400,
  bucketYellowMaxMs: 600,
  bucketOrangeMaxMs: 800,
};
