import type { IcrSettings, TrainingSettings } from '@/types';

export const DEFAULT_TRAINING_SETTINGS: TrainingSettings = {
  kochLevel: 1, // Level 1 = 2 characters, Level 2 = 3 characters, etc.
  charSetMode: 'mixed',
  digitsLevel: 1,
  mixedLettersPercent: 70,
  customSet: [],
  slidingWindowStart: 1,
  slidingWindowEnd: 40,
  sideToneMin: 400,
  sideToneMax: 600,
  volumeMin: 0.7,
  volumeMax: 1,
  linkVolume: false,
  steepness: 10,
  sessionDuration: 5,
  charsPerGroup: 5,
  numGroups: 20,
  charWpmMin: 18,
  charWpmMax: 25,
  linkCharWpm: false,
  effectiveWpmMin: 18,
  effectiveWpmMax: 25,
  linkEffectiveWpm: false,
  linkCharToEffective: true,
  echoKeyerMode: 'manual',
  extraWordSpaceMultiplier: 1,
  groupTimeout: 10,
  lockInputDuringGroupPlayback: true,
  minGroupSize: 3,
  maxGroupSize: 5,
  linkGroupSize: false,
  envelopeSmoothing: 0.75,
  qsbEnabled: true,
  qsbDepth: 0.35,
  qsbRateHz: 0.12,
  qrnEnabled: true,
  qrnLevel: 0.25,
  qrmEnabled: true,
  qrmLevel: 0.2,
  qrmProfile: 'mixed',
  receiverBackgroundGain: 20,
  receiverBackgroundExcitationRate: 62,
  receiverBackgroundResonance: 66,
  receiverBackgroundDecay: 0.984,
  receiverBackgroundOffsetHz: 140,
  receiverBackgroundOffsetModDepthHz: 45,
  receiverBackgroundOffsetModRateHz: 0.32,
  autoAdjustKoch: true,
  autoAdjustThreshold: 90,
  autoAdjustBelowThresholdCount: 1,
  autoAdjustAboveThresholdCount: 5,
  echoAutoAdjustKoch: true,
  echoAutoAdjustThreshold: 90,
  echoAutoAdjustBelowThresholdCount: 1,
  echoAutoAdjustAboveThresholdCount: 5,
  chaseLives: 3,
  chaseAutoLevelEnabled: true,
  chaseGroupsPerLevel: 5,
  chaseStartFallMs: 7200,
  chaseMinFallMs: 1800,
  chaseLevelSpeedupMs: 430,
  chaseGroupSpeedupMs: 28,
  errorWeightStrength: 3,
  charSamplingCoverageStrength: 1,
  charSamplingThompson: false,
  playerAnnounceLetters: false,
  playerLetterRepeatCount: 1,
  playerRandomizeLetters: false,
  playerDelaySeconds: 2,
  playerSpeechVoiceURI: '',
};

export const DEFAULT_ICR_SETTINGS: IcrSettings = {
  trialsPerSession: 30,
  trialDelayMs: 700,
  vadEnabled: true,
  vadThreshold: 0.08,
  vadHoldMs: 60,
  bucketGreenMaxMs: 400,
  bucketYellowMaxMs: 600,
  bucketOrangeMaxMs: 800,
};
